sudo: required

dist: trusty

language: cpp

compiler:
  - gcc

branches:
  only:
  - master

install:
  - sudo sh -c 'echo "deb http://www.icub.org/ubuntu trusty contrib/science" > /etc/apt/sources.list.d/icub.list'
  - sudo apt-get --quiet --yes update
  - sudo apt-get --quiet --yes --force-yes install icub-common
  - cd ..

  - git clone https://github.com/robotology/yarp.git
  - cd yarp
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DCREATE_LIB_MATH=TRUE ..
  - sudo make install
  - cd ../../

  - git clone https://github.com/robotology/icub-main.git
  - cd icub-main
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - sudo make install
  - cd ../../

  - git clone https://github.com/robotology/icub-contrib-common.git
  - cd icub-contrib-common
  - mkdir build
  - cd build
  - cmake ..
  - sudo make install
  - cd ../../

  - git clone https://github.com/robotology/kinect-wrapper.git
  - cd kinect-wrapper
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - sudo make install
  - cd ../../

  - cd wysiwyd

before_script:
  - cd main
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..

script:
  - make

notifications:
  email:
  - ugo.pattacini@iit.it
  - gregoire.pointeau@inserm.fr
  - anne.laure.mealier@gmail.com
  - maxpetit@gmail.com
  - jordiysard@gmail.com
  - t.fischer@imperial.ac.uk
  - matej.hoffmann@iit.it
