language: cpp

compiler:
  - gcc

env:

branches:
  only:
  - master

install:
  - sudo sh -c 'echo "deb http://www.icub.org/ubuntu precise contrib/science" > /etc/apt/sources.list.d/icub.list'
  - sudo apt-get update
  - sudo apt-get --force-yes install icub

before_script:
  - cd main
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  
script:
  - make

notifications:
  email:
  - ugo.pattacini@iit.it
  - stephane.lallee@gmail.com
  - gregoire.pointeau@inserm.fr
  - anne.laure.mealier@gmail.com
   
