version: 1.0.{build}

branches:
  only:
  - master

clone_folder: c:\wysiwyd

environment:
  GSL_DIR: c:\gsl
  IPOPT_DIR: c:\ipopt
  GTK_BASEPATH: c:\gtkmm
  GTKMM_BASEPATH: c:\gtkmm
  YARP_DIR: c:\YARP
  ICUB_DIR: c:\iCub
  WYSIWYD_DIR: c:\wysiwyd\main\build
  
install:
  - cmd: cinst wget -x86
  - cmd: cinst 7zip.commandline -x86
  
  - cmd: wget -q http://www.icub.org/download/packages/windows/msvc11/gsl-1.14-bin-msvc11.zip -O c:\gsl.zip
  - cmd: wget -q http://www.icub.org/download/packages/windows/msvc11/Ipopt-3.10.1-win32-msvc11_mumps+metis+clapack.zip -O c:\ipopt.zip
  - cmd: wget -q http://www.icub.org/download/packages/windows/common/gtkmm-2.22-0-2.zip -O c:\gtkmm.zip
  - cmd: wget -q --no-check-certificate https://googledrive.com/host/0BzentpyZAll7Z2JtblBHTkhiVDQ -O c:\yarp.zip
  - cmd: wget -q --no-check-certificate https://googledrive.com/host/0BzentpyZAll7REZwMnIzSkdJdTA -O c:\icub.zip
  - cmd: dir c:\  
  
  - cmd: 7z x c:\gsl.zip -oc:\ -y > nul
  - cmd: 7z x c:\ipopt.zip -oc:\ -y > nul 
  - cmd: 7z x c:\gtkmm.zip -oc:\ -y > nul
  - cmd: 7z x c:\yarp.zip -oc:\ -y > nul
  - cmd: 7z x c:\icub.zip -oc:\ -y > nul  
    
  - ps: rename-item c:\gsl-1.14 c:\gsl
  - ps: rename-item c:\Ipopt-3.10.1-win32-msvc11_mumps+metis+clapack c:\ipopt
  - cmd: dir c:\

build:

build_script:
  - cd c:\wysiwyd\main
  - md build
  - cd build
  - cmake -G"Visual Studio 11" ..
  - msbuild /m /p:Configuration=Release /p:Platform="Win32" wysiwyd.sln

notifications:
  email:
  - ugo.pattacini@iit.it
