version: 1.0.{build}

branches:
  only:
  - master

clone_folder: c:\projects\wysiwyd

environment:
  GSL_DIR: c:\projects\gsl
  IPOPT_DIR: c:\projects\ipopt
  GTK_BASEPATH: c:\projects\gtkmm
  GTKMM_BASEPATH: c:\projects\gtkmm
  YARP_DIR: c:\projects\YARP
  ICUB_DIR: c:\projects\iCub
  WYSIWYD_DIR: c:\projects\wysiwyd\main\build
  
install:
  - ps: (new-object net.webclient).DownloadFile('http://www.icub.org/download/packages/windows/msvc11/gsl-1.14-bin-msvc11.zip','c:\projects\gsl.zip')
  - ps: (new-object net.webclient).DownloadFile('http://www.icub.org/download/packages/windows/msvc11/Ipopt-3.10.1-win32-msvc11_mumps+metis+clapack.zip','c:\projects\ipopt.zip')
  - ps: (new-object net.webclient).DownloadFile('http://www.icub.org/download/packages/windows/common/gtkmm-2.22-0-2.zip','c:\projects\gtkmm.zip')
  - ps: (new-object net.webclient).DownloadFile('https://docs.google.com/uc?authuser=0&id=0BzentpyZAll7YkZibFEwYi1Hb2c&export=download','c:\projects\yarp.zip')
  - ps: (new-object net.webclient).DownloadFile('https://docs.google.com/uc?authuser=0&id=0BzentpyZAll7dEdBamVpVE0tMDA&export=download','c:\projects\icub.zip')
  - cmd: dir c:\projects  
  
  - ps: cinst 7zip.commandline -x86
  - ps: 7z x c:\projects\gsl.zip -oc:\projects -y > $null
  - ps: 7z x c:\projects\ipopt.zip -oc:\projects -y > $null
  - ps: 7z x c:\projects\gtkmm.zip -oc:\projects -y > $null
  - ps: 7z x c:\projects\icub.zip -oc:\projects -y > $null
  - ps: 7z x c:\projects\yarp.zip -oc:\projects -y > $null
    
  - ps: rename-item c:\projects\gsl-1.14 c:\projects\gsl
  - ps: rename-item c:\projects\Ipopt-3.10.1-win32-msvc11_mumps+metis+clapack c:\projects\ipopt

build:

build_script:
  - cd c:\projects\wysiwyd\main
  - md build
  - cd build
  - cmake -G"Visual Studio 11" ..
  - msbuild /m /p:Configuration=Release /p:Platform="Win32" wysiwyd.sln

notifications:
  email:
  - ugo.pattacini@iit.it
