version: 1.0.{build}

branches:
  only:
  - master

clone_folder: c:\dev\wysiwyd

environment:
  ACE_ROOT: c:/Program Files (x86)/robotology/ace-6.1.1
  GSL_DIR: c:/Program Files (x86)/robotology/gsl-1.14
  IPOPT_DIR: c:/Program Files (x86)/robotology/ipopt-3.10.1
  GLUT_DIR: c:/Program Files (x86)/robotology/glut-3.7.6
  GTK_BASEPATH: c:/Program Files (x86)/robotology/gtkmm-2.22.0-2
  GTKMM_BASEPATH: c:/Program Files (x86)/robotology/gtkmm-2.22.0-2
  QTDIR: c:/Program Files (x86)/robotology/qt3
  SDLDIR: c:/Program Files (x86)/robotology/sdl-1.2.13
  YARP_DIR: c:/Program Files (x86)/robotology/yarp-2.3.63
  ICUB_DIR: c:/Program Files (x86)/robotology/icub-1.1.15
  ICUBcontrib_DIR: c:/iCubContrib
  
install:
  # to install downloader do: "cinst wget -x86"
  # the format is: "wget -q URL -O c:\path-to-file\file_name"
  # special format is: wget -q --no-check-certificate URL -O c:\path-to-file\file_name
  # that accounts for downloading from e.g. https://googledrive.com/host/$HASH
  # -
  # to install unzipper do: "cinst 7zip.commandline -x86"
  # the format is: "7z x c:\path-to-archive\archive.zip -oc:\path-where-unzip -y > nul" 
  - cmd: cinst wget -x86
  
  - cmd: wget -q http://sourceforge.net/projects/yarp0/files/yarp2/yarp-2.3.63/windows/yarp_2.3.63_v11_x86_0.exe             -O c:\dev\yarp.exe
  - cmd: wget -q http://sourceforge.net/projects/robotcub/files/iCub-main/iCub-main-1.1.15/windows/iCub_1.1.15_v11_x86_0.exe -O c:\dev\icub.exe
  
  - cmd: cd c:\dev
  - cmd: yarp.exe /S
  - cmd: icub.exe /S
  - cmd: set
  
  - cmd: git clone https://github.com/robotology/icub-contrib-common.git c:\dev\icub-contrib-common
  - cmd: cd c:\dev\icub-contrib-common
  - cmd: md build
  - cmd: cd build
  - cmd: cmake -DCMAKE_INSTALL_PREFIX=c:/iCubContrib -G"Visual Studio 11" ..
  - cmd: msbuild /m /p:Configuration=Release /p:Platform="Win32" INSTALL.vcxproj

build:

build_script:
  - cd c:\dev\wysiwyd\main
  - md build
  - cd build
  - cmake -G"Visual Studio 11" ..
  - msbuild /m /p:Configuration=Release /p:Platform="Win32" wysiwyd.sln

notifications:
  email:
  - ugo.pattacini@iit.it
