version: 1.0.{build}

branches:
  only:
  - master

clone_folder: c:\wysiwyd

environment:
  GSL_DIR: c:\gsl
  IPOPT_DIR: c:\ipopt
  GTK_BASEPATH: c:\gtkmm
  GTKMM_BASEPATH: c:\gtkmm
  YARP_DIR: c:\YARP
  ICUB_DIR: c:\iCub
  WYSIWYD_DIR: c:\wysiwyd\main\build
  
install:
  - ps: (new-object net.webclient).DownloadFile('http://www.icub.org/download/packages/windows/msvc11/gsl-1.14-bin-msvc11.zip','c:\gsl.zip')
  - ps: (new-object net.webclient).DownloadFile('http://www.icub.org/download/packages/windows/msvc11/Ipopt-3.10.1-win32-msvc11_mumps+metis+clapack.zip','c:\ipopt.zip')
  - ps: (new-object net.webclient).DownloadFile('http://www.icub.org/download/packages/windows/common/gtkmm-2.22-0-2.zip','c:\gtkmm.zip')
  - ps: (new-object net.webclient).DownloadFile('https://docs.google.com/uc?authuser=0&id=0BzentpyZAll7Z2JtblBHTkhiVDQ&export=download','c:\yarp.zip')
  - ps: (new-object net.webclient).DownloadFile('https://docs.google.com/uc?export=download&confirm=huyP&id=0BzentpyZAll7REZwMnIzSkdJdTA','c:\icub.zip')
  - cmd: dir c:\  
  
  - ps: cinst 7zip.commandline -x86
  - ps: 7z x c:\gsl.zip -oc:\ -y > $null
  - ps: 7z x c:\ipopt.zip -oc:\ -y > $null
  - ps: 7z x c:\gtkmm.zip -oc:\ -y > $null
  - ps: 7z x c:\yarp.zip -oc:\ -y > $null
  - ps: 7z x c:\icub.zip -oc:\ -y > $null  
    
  - ps: rename-item c:\gsl-1.14 c:\gsl
  - ps: rename-item c:\Ipopt-3.10.1-win32-msvc11_mumps+metis+clapack c:\ipopt
  - cmd: dir c:\

build:

build_script:
  - cd c:\wysiwyd\main
  - md build
  - cd build
  - cmake -G"Visual Studio 11" ..
  - msbuild /m /p:Configuration=Release /p:Platform="Win32" wysiwyd.sln

notifications:
  email:
  - ugo.pattacini@iit.it
