version: 1.0.{build}

branches:
  only:
    - master

clone_folder: c:\projects\wysiwyd

environment:
  ace_url:   'http://www.icub.org/download/packages/windows/msvc11/ACE_6.1.0-bin-msvc11.zip'
  gsl_url:   'http://www.icub.org/download/packages/windows/msvc11/gsl-1.14-bin-msvc11.zip'
  ipopt_url: 'http://www.icub.org/download/packages/windows/msvc11/Ipopt-3.10.1-win32-msvc11_mumps+metis+clapack.zip'
  
install:
  - ps:  Write-Host "Downloading $env:ace_url ..."
  - ps:  (new-object net.webclient).DownloadFile($env:ace_url,'c:\projects\ace.zip')
  - ps:  Write-Host "Downloading $env:gsl_url ..."
  - ps:  (new-object net.webclient).DownloadFile($env:gsl_url,'c:\projects\gsl.zip')
  - ps:  Write-Host "Downloading $env:ipopt_url ..."
  - ps:  (new-object net.webclient).DownloadFile($env:ipopt_url,'c:\projects\ipopt.zip')
  
  - ps:  Write-Host "Installing 7zip ..."
  - ps:  cinst 7zip.commandline
  - ps:  Write-Host "Unpacking ace.zip ..."
  - ps:  7z x c:\projects\ace.zip   -oc:\projects -y
  - ps:  Write-Host "Unpacking gsl.zip ..."
  - ps:  7z x c:\projects\gsl.zip   -oc:\projects -y
  - ps:  Write-Host "Unpacking ipopt.zip ..."
  - ps:  7z x c:\projects\ipopt.zip -oc:\projects -y
    
  - cmd: dir c:\projects

platform: x86
configuration: Release
 
build: off
#  project: wysiwyd.sln
#  verbosity: detailed

#before_build:

#build_script:

#after_build:
