version: 1.0.{build}

branches:
  only:
  - master

clone_folder: c:\dev\wysiwyd

environment:
  GSL_DIR:           c:/Program Files (x86)/robotology/gsl-1.14
  IPOPT_DIR:         c:/Program Files (x86)/robotology/ipopt-3.10.1
  GTK_BASEPATH:      c:/Program Files (x86)/robotology/gtkmm-2.22.0-2
  GTKMM_BASEPATH:    c:/Program Files (x86)/robotology/gtkmm-2.22.0-2
  OpenCV_DIR:        c:/Program Files (x86)/robotology/opencv-git-snapshot-26-09-12
  YARP_DIR:          c:/Program Files (x86)/robotology/yarp-2.3.63
  ICUB_DIR:          c:/Program Files (x86)/robotology/icub-1.1.15
  ICUBcontrib_DIR:   c:/iCubContrib
  CMAKE_PREFIX_PATH: c:/iCubContrib

install:
  # to install unzipper do: "cinst 7zip.commandline -x86"
  # the format is: "7z x c:\path-to-archive\archive.zip -oc:\path-where-unzip -y > nul"

  - ps:  $dwntool=New-Object System.Net.WebClient
  - ps:  $dwntool.DownloadFile('http://sourceforge.net/projects/yarp0/files/yarp2/yarp-2.3.63/windows/yarp_2.3.63_v11_x86_0.exe','c:\dev\yarp.exe')
  - ps:  $dwntool.DownloadFile('http://sourceforge.net/projects/robotcub/files/iCub-main/iCub-main-1.1.15/windows/iCub_1.1.15_v11_x86_0.exe','c:\dev\icub.exe')

  - cmd: c:\dev\yarp.exe /S
  - cmd: c:\dev\icub.exe /S
  - cmd: dir "c:\Program Files (x86)\robotology"

  - cmd: git clone https://github.com/robotology/icub-contrib-common.git c:\dev\icub-contrib-common
  - cmd: cd c:\dev\icub-contrib-common
  - cmd: md build
  - cmd: cd build
  - cmd: cmake -DCMAKE_INSTALL_PREFIX=c:/iCubContrib -G"Visual Studio 11" ..
  - cmd: msbuild /m /p:Configuration=Release /p:Platform="Win32" INSTALL.vcxproj

  - cmd: git clone https://github.com/robotology/kinect-wrapper.git c:\dev\kinect-wrapper
  - cmd: cd c:\dev\kinect-wrapper
  - cmd: md build
  - cmd: cd build
  - cmd: cmake -G"Visual Studio 11" ..
  - cmd: msbuild /m /p:Configuration=Release /p:Platform="Win32" INSTALL.vcxproj

build:

build_script:
  - cd c:\dev\wysiwyd\main
  - md build
  - cd build
  - cmake -G"Visual Studio 11" ..
  - msbuild /m /p:Configuration=Release /p:Platform="Win32" wysiwyd.sln

notifications:
  - provider: Email
    to:
      - ugo.pattacini@iit.it
      - t.fischer@imperial.ac.uk
      - m.petit@imperial.ac.uk
      - anne.laure.mealier@gmail.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
