version: 1.0.{build}

branches:
  only:
  - master

clone_folder: c:\dev\wysiwyd

environment:
  GSL_DIR:         c:/dev/gsl-1.14
  IPOPT_DIR:       c:/dev/ipopt-3.10.1
  GTK_BASEPATH:    c:/dev/gtkmm-2.22.0-2
  GTKMM_BASEPATH:  c:/dev/gtkmm-2.22.0-2
  YARP_DIR:        c:/dev/yarp-2.3.63
  ICUB_DIR:        c:/dev/icub-1.1.15
  ICUBcontrib_DIR: c:/iCubContrib
  
install:
  # to install downloader do: "cinst wget -x86"
  # the format is: "wget -q URL -O c:\path-to-file\file_name"
  # special format is: "wget -q --no-check-certificate URL -O c:\path-to-file\file_name"
  # that accounts for downloading from e.g. https://googledrive.com/host/$HASH
  # -
  # to install unzipper do: "cinst 7zip.commandline -x86"
  # the format is: "7z x c:\path-to-archive\archive.zip -oc:\path-where-unzip -y > nul" 
  - cmd: cinst wget -x86
  
  - cmd: wget -q http://sourceforge.net/projects/yarp0/files/yarp2/yarp-2.3.63/windows/yarp_2.3.63_v11_x86_0.exe             -O c:\yarp.exe
  - cmd: wget -q http://sourceforge.net/projects/robotcub/files/iCub-main/iCub-main-1.1.15/windows/iCub_1.1.15_v11_x86_0.exe -O c:\icub.exe
  
  - cmd: cd c:\
  - cmd: yarp.exe /S /D=c:\dev
  - cmd: icub.exe /S /D=c:\dev
  - cmd: dir c:\dev
  - cmd: dir c:\Program Files (x86)
  
  - cmd: git clone https://github.com/robotology/icub-contrib-common.git c:\dev\icub-contrib-common
  - cmd: cd c:\dev\icub-contrib-common
  - cmd: md build
  - cmd: cd build
  - cmd: cmake -DCMAKE_INSTALL_PREFIX=c:/iCubContrib -G"Visual Studio 11" ..
  - cmd: msbuild /m /p:Configuration=Release /p:Platform="Win32" INSTALL.vcxproj

build:

build_script:
  - cd c:\dev\wysiwyd\main
  - md build
  - cd build
  - cmake -G"Visual Studio 11" ..
  - msbuild /m /p:Configuration=Release /p:Platform="Win32" wysiwyd.sln

notifications:
  email:
  - ugo.pattacini@iit.it
