version: 1.0.{build}

branches:
  only:
    - master

clone_folder: c:\projects\wysiwyd

environment:
  ACE_ROOT: c:\projects\ace
  GSL_DIR: c:\projects\gsl
  IPOPT_DIR: c:\projects\ipopt
  YARP_DIR: c:\projects\yarp\build
  ICUB_DIR: c:\projects\icub-main\build
  
install:
  - ps: (new-object net.webclient).DownloadFile('http://www.icub.org/download/packages/windows/msvc11/ACE_6.1.0-bin-msvc11.zip','c:\projects\ace.zip')
  - ps: (new-object net.webclient).DownloadFile('http://www.icub.org/download/packages/windows/msvc11/gsl-1.14-bin-msvc11.zip','c:\projects\gsl.zip')
  - ps: (new-object net.webclient).DownloadFile('http://www.icub.org/download/packages/windows/msvc11/Ipopt-3.10.1-win32-msvc11_mumps+metis+clapack.zip','c:\projects\ipopt.zip')
  
  - ps: cinst 7zip.commandline -x86
  - ps: 7z x c:\projects\ace.zip -oc:\projects -y > $null
  - ps: 7z x c:\projects\gsl.zip -oc:\projects -y > $null
  - ps: 7z x c:\projects\ipopt.zip -oc:\projects -y > $null
    
  - ps: rename-item c:\projects\ACE_wrappers c:\projects\ace
  - ps: rename-item c:\projects\gsl-1.14 c:\projects\gsl
  - ps: rename-item c:\projects\Ipopt-3.10.1-win32-msvc11_mumps+metis+clapack c:\projects\ipopt

platform: x86
configuration: Release
 
build:

before_build:
  - git clone -q --branch=master --depth=1 https://github.com/robotology/yarp.git c:\projects\yarp
  - cd c:\projects\yarp
  - md build
  - cd build
  - cmake -G"Visual Studio 11" -DCREATE_LIB_MATH:BOOL=ON ..
  - msbuild /m YARP.sln
  
  - git clone -q --branch=master --depth=1 https://github.com/robotology/icub-main.git c:\projects\icub-main
  - cd c:\projects\icub-main
  - md build
  - cd build
  - cmake -G"Visual Studio 11" -DENABLE_icubmod_cartesiancontrollerclient:BOOL=ON -DENABLE_icubmod_gazecontrollerclient:BOOL=ON ..
  - msbuild /m iCub.sln
  
build_script:
  - cd c:\projects\wysiwyd\main
  - md build
  - cd build
  - cmake -G"Visual Studio 11" ..
  - msbuild /m wysiwyd.sln


